#!/bin/bash
# Purpose: Sends an email (for example, a cron job sending job logs) using PGP enncrypted content
# Params:
# stdin 	: the message content
# $1 		: the subject line of the email
#
# Notes:
# Don't forget to make sure the recipient email matches the public key recipient you've used
# decided to hard code the recipient as this is for an automated script with a specific recipient every time

# parse the message content / pipe
# not sure this will work - will prob just sit there waiting for input due to use of ${cat} so requires piped content
messageDump=$(cat)

# set up the locals
subject="[Protected] No subject"
asciiKey=~/Keys/netsec.asc
binKey=~/Keys/sourceKey.bin
recipient="<recipient email>" 
messageDumpEncrypted=/tmp/message.txt.pgp
messageDumpTemp=/tmp/message.txt

# verify params
if [ -n "$1" ]; then
	subject=$1
fi

if [ -z "$messageDump" ]; then
	echo "No message body - nothing to send"
	exit 1 
fi

echo "$messageDump" > $messageDumpTemp

# check to see whether the binary version of the public key has been created or not
if [ ! -e $binKey ]; then
	# verify that the source pub key is in place
	if [ ! -e $asciiKey ]; then 
		echo "Must have $asciiKey to proceed"
		exit 1
	fi

	# drop ascii into bin
	gpg --dearmor < $asciiKey > $binKey
	# optionally remove the ascii public key after the bin is created
	# shred -u $asciiKey
fi

# encrypt the payload
gpg --batch --armor --trust-model always --no-default-keyring --keyring $binKey --recipient $recipient --encrypt < $messageDumpTemp > $messageDumpEncrypted

if [ -e $messageDumpEncrypted ]; then
	# content created and encrypted now send the email
	ssmtp $recipient < $messageDumpEncrypted
fi
